- hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
  - name: 'Install System Dependencies using apt'
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common 
      state: latest
      update_cache: true
  - name: 'Add the Docker apt key'
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: 'Add Docker Repository'
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  - name: 'Install Docker-CE using apt'
    apt:
     pkg:
     - docker-ce
     state: latest
     update_cache: true
  - name: 'Start Docker Service'
    service:
       name: docker
       state: started
       # - name: 'Install pip'
       # community.general.easy_install:
       #  name: pip
       #  state: latest
  - name: 'Install Python package Docker using pip'
    pip:
      name: docker

     

